webapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.welcome),
    path('load_form', views.load_form),
    path('add', views.add),
    path('show', views.show),
    path("edit/<int:id>", views.edit),
    path("update/<int:id>", views.update),
    path("delete/<int:id>", views.delete),
    path("search", views.search)



]

myapp/models.py
from django.db import models

class Employee (models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=30)

    

myapp/views.py
from django.shortcuts import render, redirect
from .models import Employee
from .Forms import EmployeeForm

def welcome(request):
    return render(request, "welcome.html")


def load_form(request):
    form = EmployeeForm
    return render(request, "mains.html", {'form' : form})

def add(request):
    form = EmployeeForm(request.POST)
    form.save()
    return redirect('/show')


def show(request):
    employee = Employee.objects.all
    return render(request, 'show.html', {'employee': employee} )


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, "edit.html", {"employee": employee})

def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    form.save()
    return redirect('/show')

def delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/show')

def search(request):
        given_name = request.POST['given_name']
        employee = Employee.objects.filter(ename__icontains = given_name)
        return render(request, 'show.html', {"employee": employee})

myapp/templates/Welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block content %}

    <h1>Welcome to home page</h1><br>
    <h1>Django python project </h1>

    <a href="load_form">Add data</a>
    <a href="show">Show data</a>

    {% endblock %}
</body>
</html>

myapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  <div class="container">
      <nav class="navbar navbar-expand-md bg-dark navbar-dark">
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
        </li>
      <li class="nav-item active"><a class="nav-link" href="/show">Show All</a></li>
      <li class="nav-item active"><a class="nav-link" href="/load_form">Add New</a></li>
    </ul>
    <form method="POST" action="search" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
      <input name="given_name" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{%block content%}}
{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</div>
  </body>

</html>

myapp/templates/edit.html
{% extends 'base.html' %}


<body>
{% block content %}
<form method="POST" action="/update/{{ employee.id }}">
    {% csrf_token %}
<table>
    <tr><td><input type="text" name="eid" required maxlength="15" value="{{ employee.eid }}"/></td></tr>
    <tr><td><input type="text" name="ename" required maxlength="100" id="id_ename" value="{{ employee.ename }}"/></td></tr>
    <tr><td><input type="email" name="eemail" required maxlength="254" id="id_eemail" value="{{ employee.eemail }}"/></td></tr>
    <tr><td><input type="text" name="econtact" required maxlength="15" id="id_econtact" value="{{ employee.econtact }}"/></td></tr>
    <tr><td><button type="submit">Update</button></td></tr>
</table>
</form>
{% endblock %}
</body>

myapp/templates/mains.html
{% extends 'base.html' %}


<body>
{% block content %}
<form method="post" action="/add">
    {% csrf_token %}

    <label>ID: </label>
    <div>{{ form.eid }}</div>
    <label>Name: </label>
    <div>{{ form.ename }}</div>
    <label>Email:</label>
    <div> {{ form.eemail }}</div>
    <label>Contact:</label>
    <div> {{ form.econtact }}</div>
    <div>
        <button class="btn btn-info" type="submit">Add</button>
    </div>

</form>

{% endblock %}
</body>

myapp/templates/show.html
{% extends 'base.html' %}



<body>
{% block content %}
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>MID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Contact</th>
    </tr>
    {% for i in employee%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.eid}}</td>
        <td>{{i.ename}}</td>
        <td>{{i.eemail}}</td>
        <td>{{i.econtact}}</td>
        <td><a href="/edit/{{ i.id }}">Edit</a></td>
        <td><a href="/delete/{{ i.id }}">delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}
</body>